{% set version = "1.2-21.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lasso2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lasso2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lasso2/lasso2_{{ version }}.tar.gz
  sha256: 87c8449cd436332566fba7dcf21f5f2b33cd6e0a5ee2e95d3c3888d58c15e95e

build:
  merge_build_host: true  # [win]
  number: 0
  skip: True  # [r_base < "4.0.0"]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('lasso2')"           # [not win]
    - "\"%R%\" -e \"library('lasso2')\""  # [win]

about:
  home: http://www.maths.uwa.edu.au/~berwin/software/lasso.html
  license: GPL-2.0-or-later
  summary: Routines and documentation for solving regression problems while imposing an L1 constraint on the estimates, based on the algorithm of Osborne et al. (1998).
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: lasso2
# Version: 1.2-20
# Date: 2018-11-27
# Author: Justin Lokhorst, Bill Venables and Berwin Turlach; port to R, tests etc: Martin Maechler <maechler@stat.math.ethz.ch>
# Maintainer: Berwin Turlach <Berwin.Turlach@gmail.com>
# Title: L1 Constrained Estimation aka `lasso'
# Description: Routines and documentation for solving regression problems while imposing an L1 constraint on the estimates, based on the algorithm of Osborne et al. (1998).
# Depends: R (>= 3.2.3)
# License: GPL (>= 2)
# URL: http://www.maths.uwa.edu.au/~berwin/software/lasso.html
# Packaged: 2018-11-27 08:49:28 UTC; berwin
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2018-11-27 09:30:03 UTC
