appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: jvjAWgUIKyLYElkdsXPJgk6dev7/jXrb2bEEBqpgvz1V8B4zfbHSyTN17EDntfMEUZ3ALVEc6rwdzLwWX+lDuI5tDkxBqhKPeLkogsb6HnLjvZqEWocX3+Kis9kTdTcYwrgFd7GhI4gROK+98sfcaBsrfWJazwjERgqIzM3YziacfP6zf3oG5D4hjnEQ5OE2rP7lKVz7xlVhPqrWrf7c7LpBnDgpslmTc3ZuMD/m9tWJ39B4FI1dH+Zry/nIk7sm0uXQTxKTOGj8pwCBhAa7FASjnQB5xS/uYv9UAzPChiopSptK5rmt56nbATDqX+sO1w97kAoL4gBIckYDlMn7cU2epjYkmE++goLhg3C/s0kIxjTH2jfecB0Uu+Whwc7K008/Jd2ylJxOCpYN4TVZnJEDZF+6VB/Qq39O9Q5bi4m3epQCCSkmpcPjssj7z2j8CdZO3sBzDeADuiY3FOCvx8udY3Vu+Jx7V5pAQgnJb9invj0/JHEEhUSPlw6J5stCDBeYozrWIFvaiBCdVQBvGTN3YmFer0OI+on287S4xH85Bx13AA2nJNDH4mmU/ayraNZ002ccfHF/95QGrVEWKEcabh6+PVx0x1ntSjZnXTl9u4t+PyD+gCX/EBz/tMyKOfool+gNlFbXxi1ZrAprWp0IAhb99W8xQBHWDaY5Gaw=}
